import { getLocales } from "expo-localization";

export const Translate = (textKey) => {
  const locales = getLocales();
  const languageCode = locales[0].languageCode;
  const translationsForLanguage =
    languageCode == "vi" ? translations["vi"] : translations["en"];
  return translationsForLanguage[textKey] || textKey;
};
const translations = {
  en: {
    version: "Version",
    signin: "Sign in",
    toyour: "to your",
    account: "account",
    username: "Username",
    password: "Password",
    signin: "Sign in",
    youdonothaveanaccount: "You do not have an account",
    signup: "Sign up",
    orsigninwith: "Or sign in with",
    createyouraccount: "create your account",
    fullname: "fullname",
    password: "Password",
    createyouraccount: "Create your account",
    alreadyhaveanaccount: "Already have an account?",
    accountnamereg: "Username (6 characters or more)",
    fullnamereg: "Full name (max 20 characters)",
    passwordreg: "Password (8 characters or more)",
    confirmpassword: "Confirm password",
    notice: "Notice",
    pleasefullinfor: "Please enter full information",
    incorrectlogininformation: "Incorrect login information",
    wellcome: "Wellcome",
    newchat: "Newchat",
    chat: "Chat",
    chathistory: "Chat History",
    theme: "Theme",
    logout: "Logout",
    selectphoto: "Select photo",
    library: "Library",
    takephoto: "Take photo",
    entermessage: "Enter message",
    cancel: "Cancel",
    confirm: "Confirm",
    wantdeletethischat: "Do you want to delete this chat?",
    light: "Light",
    dark: "Dark",
    device: "By device",
  },
  vi: {
    version: "Phiên bản",
    signin: "Đăng nhập",
    toyour: "tài khoản",
    account: "của bạn",
    username: "Tên người dùng",
    password: "Mật khẩu",
    youdonothaveanaccount: "Bạn chưa có tài khoản",
    signup: "Đăng ký",
    orsigninwith: "Hoặc đăng nhập bằng",
    createyouraccount: "Tạo tài khoản của bạn",
    accountname: "Tên tài khoản",
    password: "Mật khẩu",
    createyouraccount: "Tạo tài khoản của bạn?",
    alreadyhaveanaccount: "Đã có tài khoản?",
    accountnamereg: "Tên tài khoản (6 ký tự trở lên)",
    fullnamereg: "Họ tên (tối đa 20 ký tự)",
    passwordreg: "Mật khẩu (8 ký tự trở lên)",
    confirmpassword: "Xác nhận mật khẩu",
    notice: "Thông báo",
    pleasefullinfor: "Hãy nhập đầy đủ thông tin",
    incorrectlogininformation: "Thông tin đăng nhập không đúng",
    wellcome: "Chào mừng",
    newchat: "Trò chuyện mới",
    chat: "Trò chuyện",
    chathistory: "Lịch sử trò chuyện",
    theme: "Chủ đề",
    logout: "Đăng xuất",
    selectphoto: "Chọn ảnh",
    library: "Thư viện",
    takephoto: "Chụp ảnh",
    entermessage: "Nhập tin nhắn",
    cancel: "Huỷ bỏ",
    confirm: "Xác nhận",
    wantdeletethischat: "Bạn muốn xoá đoạn chat này?",
    light: "Sáng",
    dark: "Tối",
    device: "Theo thiết bị",
  },
};
